
AADR_url: "https://reichdata.hms.harvard.edu/pub/datasets/amh_repo/curated_releases/V50/V50.0/SHARE/public.dir/v50.0_1240K_public.tar"
Patterson2022_url: "https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/Genotype.dataset_0.zip"
Fowler2021_url: "https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/Fowler_Genotypes_Hazleton.zip"